[theme]
primaryColor = "#9C27B0"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F3E5F5"
textColor = "#212121"
font = "sans serif"

[server]
headless = true
enableCORS = false

[browser]
gatherUsageStats = false 