# This is a template for Streamlit Cloud's secrets
# In Streamlit Cloud, go to Settings > Secrets and add these key-value pairs
# Replace "your_openai_api_key_here" with your actual API key

OPENAI_API_KEY = "your_openai_api_key_here" 